cc_library(
    name="factor_graph",
    srcs=["factor_graph.hpp", "layout_data.h"],
    hdrs=["factor_graph.hpp", "layout_data.h"],
    deps=[
        "@com_github_skypjack_entt//:entt",
        "@com_gitlab_libeigen_eigen//:eigen",
        "//math:gaussian_math",
        "//util:eigen_util",
    ],
    visibility=['//visibility:public']
)
